language: generic
deploy:
- provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: somleng-freeswitch
  env: somleng-freeswitch-webserver
  bucket_name: deploy.somleng.org
  on:
    repo: somleng/freeswitch-config
    branch: master
