services:
  - docker

before_install:
  - docker build -t somleng/somleng-freeswitch .

script:
  - docker run --rm somleng/somleng-freeswitch /usr/bin/freeswitch -version

deploy:
- provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: somleng-freeswitch
  env: somleng-freeswitch-webserver
  bucket_name: deploy.somleng.org
  on:
    repo: somleng/freeswitch-config
    branch: master
